import { Platform, StyleSheet } from "react-native";
import { Colors } from "../../src/constants/Theme";

export const shadow = Platform.select({
  ios: {
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.09,
    shadowRadius: 16,
  },
  android: { elevation: 6 },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F6FB",
  },
  scrollContent: {
    paddingBottom: 48,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4F6FB",
  },

  // ─── Hero Header ───────────────────────────────────────────────────────────
  heroHeader: {
    backgroundColor: Colors.white,
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 20,
    overflow: "hidden",
    ...shadow,
  },
  heroGradientOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.blue,
    opacity: 0.02,
  },
  heroCircle1: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: Colors.blue,
    opacity: 0.04,
  },
  heroCircle2: {
    position: "absolute",
    bottom: -20,
    left: -30,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: Colors.orange,
    opacity: 0.05,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTextBlock: {
    flex: 1,
  },
  greeting: {
    fontSize: 30,
    fontWeight: "900",
    color: Colors.navy,
    letterSpacing: -0.8,
  },
  greetingAccent: {
    color: Colors.blue,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.slate[400],
    marginTop: 4,
  },
  logoWrapper: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: Colors.blue + "08",
    alignItems: "center",
    justifyContent: "center",
  },
  headerLogo: {
    width: 44,
    height: 36,
    opacity: 0.18,
  },
  kidSwitcher: {
    marginTop: 20,
  },
  kidTab: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: "#F4F6FB",
    marginRight: 10,
    borderWidth: 1,
    borderColor: Colors.slate[100],
  },
  kidTabActive: {
    backgroundColor: Colors.blue,
    borderColor: Colors.blue,
  },
  kidTabText: {
    fontSize: 13,
    fontWeight: "800",
    color: Colors.navy,
  },
  kidTabTextActive: {
    color: Colors.white,
  },

  // ─── Kid Mode Card ─────────────────────────────────────────────────────────
  kidModeCardWrapper: {
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 20,
    overflow: "hidden",
    ...shadow,
  },
  kidModeCardInner: {
    backgroundColor: Colors.navy,
    borderRadius: 20,
    overflow: "hidden",
  },
  kidModeGlow: {
    position: "absolute",
    top: -30,
    right: -20,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: Colors.orange,
    opacity: 0.15,
  },
  kidModeContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    gap: 14,
  },
  kidModeIconBg: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: Colors.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  flex1: { flex: 1 },
  row: { flexDirection: "row", alignItems: "center" },
  kidModeTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: Colors.white,
  },
  kidModeDesc: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.55)",
    marginTop: 2,
  },
  kidModeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.teal + "25",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginLeft: 10,
    borderWidth: 1,
    borderColor: Colors.teal + "40",
  },
  kidModeBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    color: Colors.teal,
  },
  arrowIconFilled: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },

  // ─── Stats ─────────────────────────────────────────────────────────────────
  statsRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 18,
    padding: 14,
    borderTopWidth: 3,
    alignItems: "flex-start",
    ...shadow,
  },
  statIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  statValue: {
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: -1,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: Colors.slate[400],
    marginTop: 2,
  },

  // ─── Section headers ───────────────────────────────────────────────────────
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.blue,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: Colors.slate[400],
    letterSpacing: 1.2,
  },
  sectionLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  sectionLink: {
    fontSize: 11,
    fontWeight: "900",
    color: Colors.blue,
    letterSpacing: 0.5,
  },

  // ─── Booking card ──────────────────────────────────────────────────────────
  bookingCardOuter: {
    backgroundColor: Colors.white,
    borderRadius: 22,
    overflow: "hidden",
    ...shadow,
  },
  bookingStripe: {
    padding: 20,
    paddingBottom: 22,
  },
  bookingStripeContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  bookingTypePill: {
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  bookingTypePillText: {
    fontSize: 10,
    fontWeight: "900",
    color: Colors.white,
    letterSpacing: 0.4,
  },
  bookingStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: Colors.white,
  },
  bookingStatusText: {
    fontSize: 10,
    fontWeight: "900",
    color: Colors.white,
  },
  bookingStripeTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: Colors.white,
    letterSpacing: -0.3,
  },
  bookingBody: {
    padding: 20,
  },
  bookingInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
    backgroundColor: "#F4F6FB",
    borderRadius: 14,
    padding: 12,
    gap: 0,
  },
  bookingInfoItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  bookingInfoIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  bookingInfoText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.navy,
    textTransform: "capitalize",
  },
  bookingInfoDivider: {
    width: 1,
    height: 24,
    backgroundColor: Colors.slate[100],
    marginHorizontal: 8,
  },
  bookingActions: {
    flexDirection: "row",
    gap: 12,
  },
  joinBtnNew: {
    flex: 2,
    height: 50,
    backgroundColor: Colors.orange,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  joinBtnNewText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "900",
  },
  manageBtn: {
    flex: 1,
    height: 50,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Colors.blue + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  manageBtnText: {
    color: Colors.blue,
    fontSize: 14,
    fontWeight: "800",
  },

  // ─── Empty booking ─────────────────────────────────────────────────────────
  emptyBookingCard: {
    backgroundColor: Colors.white,
    borderRadius: 22,
    padding: 28,
    alignItems: "center",
    ...shadow,
  },
  emptyBookingIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.blue + "08",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "900",
    color: Colors.navy,
    marginBottom: 6,
  },
  emptyDesc: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.slate[400],
    textAlign: "center",
    marginBottom: 20,
  },
  reserveBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: Colors.blue + "40",
  },
  reserveBtnText: {
    fontSize: 13,
    fontWeight: "900",
    color: Colors.blue,
  },

  // ─── Level card ────────────────────────────────────────────────────────────
  levelCard: {
    backgroundColor: Colors.navy,
    borderRadius: 22,
    padding: 20,
    overflow: "hidden",
    ...shadow,
  },
  levelCardGlow: {
    position: "absolute",
    top: -40,
    right: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    opacity: 0.5,
  },
  levelCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  levelBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
  },
  levelBadgeText: {
    fontSize: 13,
    fontWeight: "900",
  },
  levelTitleBlock: {
    flex: 1,
  },
  levelName: {
    fontSize: 16,
    fontWeight: "900",
    color: Colors.white,
  },
  levelSub: {
    fontSize: 11,
    fontWeight: "600",
    color: "rgba(255,255,255,0.45)",
    marginTop: 1,
  },
  trophyCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  progressTrack: {
    height: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 10,
  },
  progressFill: {
    height: "100%",
    borderRadius: 4,
  },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressPct: {
    fontSize: 11,
    fontWeight: "800",
    color: "rgba(255,255,255,0.6)",
  },
  progressMilestone: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  progressMilestoneText: {
    fontSize: 11,
    fontWeight: "800",
    color: Colors.teal,
  },

  // ─── Quick actions ─────────────────────────────────────────────────────────
  quickGrid: {
    flexDirection: "row",
    gap: 12,
  },
  quickItem: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    ...shadow,
  },
  quickItemIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  quickItemLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: Colors.slate[400],
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  quickItemTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: Colors.navy,
  },

  // ─── Activity ──────────────────────────────────────────────────────────────
  activityCard: {
    backgroundColor: Colors.white,
    borderRadius: 22,
    overflow: "hidden",
    ...shadow,
  },
  activityItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F4F6FB",
    gap: 12,
  },
  activityIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activityTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.navy,
  },
  activityDate: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.slate[400],
    marginTop: 2,
  },
  scoreBadge: {
    backgroundColor: Colors.teal + "12",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  scoreText: {
    fontSize: 11,
    fontWeight: "900",
    color: Colors.teal,
  },

  // ─── Support ───────────────────────────────────────────────────────────────
  supportCard: {
    backgroundColor: Colors.white,
    borderRadius: 18,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    ...shadow,
  },
  supportLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  supportIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  supportTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: Colors.navy,
  },
  supportSubtitle: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.slate[400],
    marginTop: 2,
  },
  supportBtn: {
    backgroundColor: Colors.teal + "15",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.teal + "30",
  },
  supportBtnText: {
    fontSize: 13,
    fontWeight: "900",
    color: Colors.teal,
  },
});
