import { Platform, StyleSheet } from "react-native";
import { Colors } from "../../src/constants/Theme";

export const shadow = Platform.select({
  ios: {
    shadowColor: Colors.navy,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.09,
    shadowRadius: 16,
  },
  android: { elevation: 6 },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F6FB",
  },
  scrollContent: {
    paddingBottom: 48,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4F6FB",
  },
  decorCircle: {
    position: "absolute",
    top: -60,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: Colors.blue,
    opacity: 0.03,
  },
  // ─── Hero Header ───────────────────────────────────────────────────────────
  heroHeader: {
    backgroundColor: Colors.white,
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 20,
    overflow: "hidden",
    ...shadow,
  },
  heroGradientOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.blue,
    opacity: 0.02,
  },
  heroCircle1: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: Colors.blue,
    opacity: 0.04,
  },
  heroCircle2: {
    position: "absolute",
    bottom: -20,
    left: -30,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: Colors.orange,
    opacity: 0.05,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTextBlock: {
    flex: 1,
  },
  greeting: {
    fontSize: 30,
    fontWeight: "900",
    color: Colors.navy,
    letterSpacing: -0.8,
  },
  greetingAccent: {
    color: Colors.blue,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.slate[400],
    marginTop: 4,
  },
  logoWrapper: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: Colors.blue + "08",
    alignItems: "center",
    justifyContent: "center",
  },
  headerLogo: {
    width: 44,
    height: 36,
    opacity: 0.18,
  },
  flex1: { flex: 1 },
  row: { flexDirection: "row", alignItems: "center" },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: Colors.blue + "10",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  creditsCard: {
    padding: 0,
  },
  creditsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  creditsIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.gold + "15",
    borderWidth: 1,
    borderColor: Colors.gold + "25",
    alignItems: "center",
    justifyContent: "center",
  },
  creditsLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: Colors.slate[400],
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  creditsValue: {
    fontSize: 22,
    fontWeight: "900",
    color: Colors.navy,
    marginTop: 2,
  },
  creditsHint: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.slate[400],
    marginTop: 2,
  },
  reserveBtn: {
    minWidth: 90,
  },
  reserveBtnText: {
    color: Colors.white,
    fontWeight: "900",
    fontSize: 13,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: Colors.blue + "10",
    borderWidth: 1,
    borderColor: Colors.blue + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: Colors.navy,
  },
  dashboardLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  dashboardLinkText: {
    fontSize: 13,
    fontWeight: "800",
    color: Colors.blue,
  },
  bookingList: {
    paddingHorizontal: 24,
    gap: 16,
    marginBottom: 8,
  },
  bookingCard: {
    padding: 0,
  },
  bookingTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  bookingDate: {
    fontSize: 16,
    fontWeight: "900",
    color: Colors.navy,
    textTransform: "capitalize",
  },
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  timeText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.slate[400],
  },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
  },
  typeBadgeTrial: {
    backgroundColor: Colors.orange + "12",
    borderColor: Colors.orange + "25",
  },
  typeBadgeRegular: {
    backgroundColor: Colors.blue + "12",
    borderColor: Colors.blue + "25",
  },
  typeBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.slate[100],
    marginBottom: 16,
  },
  bookingMainRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 20,
  },
  starWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.gold + "12",
    borderWidth: 1,
    borderColor: Colors.gold + "25",
    alignItems: "center",
    justifyContent: "center",
  },
  courseTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: Colors.navy,
  },
  courseKid: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.slate[400],
    marginTop: 2,
  },
  kidNameAccent: {
    color: Colors.blue,
    fontWeight: "800",
  },
  bookingActions: {
    gap: 10,
  },
  joinBtn: {
    backgroundColor: Colors.blue,
    borderBottomColor: Colors.deepBlue,
  },
  joinBtnText: {
    color: Colors.white,
    fontWeight: "900",
    fontSize: 15,
  },
  emptyCard: {
    padding: 0,
  },
  emptyContent: {
    alignItems: "center",
    paddingVertical: 32,
    paddingHorizontal: 24,
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: Colors.beige,
    borderWidth: 1,
    borderColor: Colors.slate[100],
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: Colors.navy,
  },
  emptySubtitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.slate[400],
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
    maxWidth: 280,
  },
  emptyBtn: {
    marginTop: 28,
    paddingHorizontal: 28,
    backgroundColor: Colors.blue,
    borderBottomColor: Colors.deepBlue,
  },
  emptyBtnText: {
    color: Colors.white,
    fontWeight: "900",
  },
  pastList: {
    gap: 10,
  },
  pastCard: {
    padding: 0,
  },
  pastRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pastDate: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.slate[500],
    textTransform: "capitalize",
  },
});
